#!/usr/bin/env bash
# Sparse-checkout Ray documentation (Apache 2.0) into content/raw/.
#
# Source: https://github.com/ray-project/ray  (doc/source/)
# License: Apache 2.0 — freely usable, redistributable, and committable to GitHub.
#
# Sections included (prose + how-to pages only):
#   ray-overview    — installation, getting-started
#   ray-core        — tasks, actors, objects, scheduling, fault tolerance
#   serve           — model serving, deployments, LLM serving
#   train           — distributed training (PyTorch, HuggingFace, etc.)
#   tune            — hyperparameter tuning
#   data            — distributed data processing
#   ray-observability — monitoring, debugging, logging
#
# Sections excluded:
#   cluster         — cloud-provider-specific setup (AWS/GCP/Azure); too ops-heavy
#   rllib           — reinforcement learning; separate domain, adds noise
#
# Within each section, the following are excluded:
#   api/            — auto-generated API reference (.. autosummary:: stubs)
#   doc/            — per-method auto-generated stubs
#   doc_code/       — raw Python example files (no prose value)
#   examples/       — notebooks/scripts, not prose documentation
#   images/         — binary assets
#   benchmarks.rst  — performance benchmarks, not conceptual/task content
#   deprecated-*/   — deprecated content

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
RAW_DIR="$REPO_ROOT/content/raw"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

# ---------------------------------------------------------------------------
# Sections to sparse-checkout from ray-project/ray
# ---------------------------------------------------------------------------
# Each entry is a path within the repo.  We only pull what we need — the
# full Ray repo is enormous (Ray source + tests + python bindings).
SUBSET=(
  doc/source/ray-overview
  doc/source/ray-core
  doc/source/serve
  doc/source/train
  doc/source/tune
  doc/source/data
  doc/source/ray-observability
)

echo ">> Sparse-cloning ray-project/ray (blobless, depth 1)..."
git clone --filter=blob:none --depth 1 --sparse \
  https://github.com/ray-project/ray.git "$WORK/ray"
git -C "$WORK/ray" sparse-checkout set "${SUBSET[@]}"

# ---------------------------------------------------------------------------
# Copy prose files into content/raw/, filtering out non-prose directories
# ---------------------------------------------------------------------------
# We want .rst and .md files that are human-written prose.
# We skip:
#   - api/         auto-generated API reference
#   - doc/         per-method stubs generated by autosummary
#   - doc_code/    raw Python snippets (no prose value on their own)
#   - examples/    notebook/script examples
#   - images/      binary assets
#   - benchmarks*  performance data files
#   - deprecated-* old content

echo ">> Copying prose files into $RAW_DIR ..."
rm -rf "$RAW_DIR"; mkdir -p "$RAW_DIR"

for section_path in "${SUBSET[@]}"; do
  # section_name = "ray-core", "serve", "train", etc.
  section_name="$(basename "$section_path")"
  src="$WORK/ray/$section_path"

  find "$src" -type f \( -name '*.rst' -o -name '*.md' \) | while read -r f; do
    # Build the relative path within this section, e.g. "actors/out-of-band.rst"
    rel="${f#$src/}"

    # Skip directories and files we don't want.
    # Match against path components so partial names don't cause false positives.
    case "$rel" in
      api/*|*/api/*)         continue ;;  # auto-generated API reference stubs
      doc/*|*/doc/*)         continue ;;  # per-method autosummary stubs
      doc_code/*|*/doc_code/*) continue ;; # raw Python code snippets
      examples/*|*/examples/*) continue ;; # notebook/script examples
      images/*|*/images/*)   continue ;;  # binary assets
      benchmarks*|*/benchmarks*) continue ;; # performance benchmark files
      deprecated-*|*/deprecated-*) continue ;; # deprecated content
      _*)                    continue ;;  # Sphinx internal files (_includes, etc.)
    esac

    dest="$RAW_DIR/$section_name/$rel"
    mkdir -p "$(dirname "$dest")"
    cp "$f" "$dest"
  done
done

# ---------------------------------------------------------------------------
# Report
# ---------------------------------------------------------------------------
MD_COUNT=$(find "$RAW_DIR" -name '*.md' | wc -l | tr -d ' ')
RST_COUNT=$(find "$RAW_DIR" -name '*.rst' | wc -l | tr -d ' ')
TOTAL=$(( MD_COUNT + RST_COUNT ))

echo ""
echo ">> Done: $TOTAL files in content/raw/  ($MD_COUNT .md, $RST_COUNT .rst)"
echo "   (Apache 2.0, The Ray Authors — ray-project/ray)"
echo ""
echo "Section breakdown:"
for section_path in "${SUBSET[@]}"; do
  section_name="$(basename "$section_path")"
  count=$(find "$RAW_DIR/$section_name" -type f \( -name '*.rst' -o -name '*.md' \) 2>/dev/null | wc -l | tr -d ' ')
  printf "   %-22s %s files\n" "$section_name" "$count"
done
echo ""
echo "Next: make enrich"
